from .configuration_stylegan_disc import StyleGANDiscriminatorConfig
from .configuration_vit_vqgan import ViTVQConfig
from .modeling_stylegan_disc import StyleGANDiscriminator
from .modeling_vit_vqgan import ViTVQModel
